version: '3.9'

services:
  # Сервис для разворачивания контейнера с приложением
  app:
    ports:
      - "8080:8080"
    build:
      context: .
#    depends_on:
#      - database
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/animal-chipization
#      - POSTGRES_USER=user
#      - POSTGRES_PASSWORD=password


  # Сервис для разворачивания контейнера с автотестами
  tests:
    image: mrexpen/planet_olymp_phase1
    pull_policy: always
    ports:
      - "8090:8080"
    depends_on:
      - app
    environment:
      SERVER_URL: http://app:8080
      STAGE: 0
      # 0, 1 или 2 - запуск тестов для соответствующего этапа
      # all - запуск всех тестов из трёх доступных этапов
